
- name: Update repositories and all packages on target machine
  apt:
    name: "*"
    update_cache: yes

- name: Install necessary utils on target machine
  apt:
    pkg:
     - swatch

- name: Ensure group "webhook" exists
  group:
    name: webhook
    gid: 1000
    state: present

- name: Add the disabled user account 'swatchdog' with a primary group of 'webhook'
  user:
    name: swatchdog
    comment: Swatch user account for login monitoring.
    password: '!'
    shell: /bin/bash
    uid: 1001
    group: webhook
    
- name: Collect the location of the awx_web containers log
  shell: "/usr/bin/docker inspect --format '{''{.LogPath}''}' awx_web"
  register: log_location

- name: Create a symbolic link to the awx_web containers log
  file:
    src: "{{ log_location.stdout }}"
    dest: /var/log/awx_web.log
    owner: swatchdog
    group: webhook
    state: link

- name: Install swatchdog.conf
  copy:
    src: "{{ role_path }}/swatchdog.conf"
    dest: /etc/swatchdog.conf
    owner: root
    group: root
    mode: '0644'
    
- name: Install bind-user.py script
  copy:
    src: "{{ role_path }}/bind-user.py"
    dest: /usr/local/bin/bind-user.py
    owner: swatchdog
    group: webhook
    mode: '0550'

- name: Fetch the awx_tokens.yml variable from AWX again
  fetch:
    src: /var/lib/awx/projects/hosting/awx_tokens.yml
    dest: /tmp/awx_tokens.yml
    flat: yes

- name: Include AWX master token from awx_tokens.yml
  include_vars:
    file: /tmp/awx_tokens.yml
  no_log: True

- name: Save bind-user.yml template
  template:
    src: '{{ role_path }}/bind-user.yml.j2'
    dest: '/usr/local/bin/bind-user.yml'
    owner: root
    group: root
    mode: '0755'

- name: Swatchdog systemd unit
  copy:
    src: "{{ role_path }}/swatchdog.service"
    dest: /etc/systemd/system/swatchdog.service
    owner: root
    group: root
    mode: '0644'

- name: Touch the swatchdog PID file
  file:
    path: /run/swatchdog.pid
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Just force systemd to daemon-reload
  systemd:
    daemon_reload: yes
    
- name: Make sure swatchdog service is started
  systemd:
    state: started
    name: swatchdog
    
- name: Make sure swatchdog service is enabled
  systemd:
    enabled: yes
    name: swatchdog

- name: Install awx.awx collection for ansible
  command: |
    runuser -u swatchdog -- bash -c 'ansible-galaxy collection install --force awx.awx:17.1.0'
