
- block:
  - name: Collect Debian version from AWX server
    command: lsb_release -c
    register: debian_version

  - name: Setting facts for checking the release
    set_fact:
      buster_string: "buster"
      bullseye_string: "bullseye"

  - name: Add buster-backports repository into sources list
    apt_repository:
      repo: deb http://deb.debian.org/debian buster-backports main
      state: present
    when: buster_string in debian_version.stdout

  - name: Install FreeRADIUS packages for Debian 10
    apt:
      pkg:
       - freeradius
       - freeradius-python3
       - python3-requests-oauthlib
      default_release: buster-backports
    when: buster_string in debian_version.stdout

  - name: Install FreeRADIUS packages for Debian 11
    apt:
      pkg:
       - freeradius
       - freeradius-python3
       - python3-requests-oauthlib
    when: bullseye_string in debian_version.stdout

  - name: Force FreeRADIUS auth-type PAP
    lineinfile:
      path: '/etc/freeradius/3.0/users'
      line: "DEFAULT\t\tAuth-Type = pap"

  - name: Install custom exec module
    copy:
      src: "{{ role_path }}/exec"
      dest: '/etc/freeradius/3.0/mods-available/'
      owner: root
      group: root
      mode: '0644'

  - name: Install FreeRADIUS exec mod enabled link
    file:
      src: '/etc/freeradius/3.0/mods-available/exec'
      dest: '/etc/freeradius/3.0/mods-enabled/exec'
      owner: freerad
      group: freerad
      state: link

# need to ensure /run/freeradius or whatever exists! debian 11 bug :o

  - name: Ensure /var/run/freeradius directory exists, prevents this Debian 11 bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954911
    file:
      path: '/var/run/freeradius'
      state: directory
      owner: freerad
      group: freerad
      mode: '0770'

# create new wp-oracle user account, make sure it's disabled/passwordless

  - name: Ensure group "wp-oracle" exists
    group:
      name: wp-oracle
      gid: 1002
      state: present

  - name: Add the disabled user account 'wp-oracle' with a specific uid and a primary group of 'webhook'
    user:
      name: wp-oracle
      comment: "WP-Oracle account for checking front-end logins."
      password: '!'
      shell: /bin/bash
      uid: 1002
      group: wp-oracle

  - name: Template the wp-oracle.py file
    template:
      src: "{{ role_path }}/wp-oracle.py.j2"
      dest: /usr/local/bin/wp-oracle.py
      owner: freerad
      group: freerad
      mode: '0555'

#  - name: Template the oauth2-oracle.py file
#    template:
#      src: "{{ role_path }}/oauth2-oracle.py.j2"
#      dest: /usr/local/bin/oauth2-oracle.py
#      owner: root
#      group: root
#      mode: '0750'

# ensure ssh key created in /home/wp-oracle/.ssh/auth_{{ wp_url }}_ed25519

  - name: Ensure the ~/.ssh directory exists on front-end wordpress site
    delegate_to: "{{ wp_url }}"
    become: no
    file:
      path: "/home/{{ wp_username }}/.ssh/"
      state: directory
      mode: '0750'

  - name: Generate OpenSSH key for wp-oracle user to connect to front-end
    #delegate_to: "{{ wp_url }}"
    #become: no
    community.crypto.openssh_keypair:
      path: '/home/wp-oracle/.ssh/wp-oracle_ed25519'
      comment: 'WP-Oracle SSH key for {{ wp_url }}'
      type: ed25519
      mode: '0600'

# slurp up public_key value

  - name: Collect SSH public key value
    #delegate_to: "{{ wp_url }}"
    #become: no
    command: |
        cat /home/wp-oracle/.ssh/wp-oracle_ed25519.pub
    register: public_key

  - name: Update SSH config on AWX system
    blockinfile:
      path: /home/wp-oracle/.ssh/config
      create: yes
      block: |
        Host {{ wp_url }}
            HostName {{ wp_url }}
            Port 22
            User {{ wp_username }}
            IdentityFile /home/wp-oracle/.ssh/wp-oracle_ed25519
            IdentitiesOnly=yes

# add public key to front-end server /home/{{ wp_user }}/.ssh/authorized_keys

  - name: Add wp-oracle public SSH key to the front-end wordpress site
    delegate_to: "{{ wp_url }}"
    become: no
    blockinfile:
      path: "/home/{{ wp_username }}/.ssh/authorized_keys"
      create: yes
      block: |
        {{ public_key.stdout }} command=/home/{{ wp_username }}/wp-probe.sh
      mode: '0660'

# template wp-probe on the front-end site

  - name: Template the wp-probe.sh file onto the front-end wordpress site
    delegate_to: "{{ wp_url }}"
    become: no
    template:
      src: "{{ role_path }}/wp-probe.sh.j2"
      dest: "/home/{{ wp_username }}/wp-probe.sh"
      mode: '0550'

  - name: Setup custom sudoers file to allow freeradius > wp-oracle commands
    blockinfile:
      path: /etc/sudoers.d/50-freerad-wp
      create: yes
      block: |
        # Allow freerad user to execute /usr/local/bin/wp-oracle, could definitely be tightened!!
        freerad ALL=(ALL:ALL) NOPASSWD:ALL
      mode: 600

  - name: Install custom default config
    copy:
      src: "{{ role_path }}/default"
      dest: '/etc/freeradius/3.0/sites-available/default'
      owner: root
      group: root
      mode: '0644'
      
  - name: Install FreeRADIUS default site enabled link
    file:
      src: '/etc/freeradius/3.0/sites-available/default'
      dest: '/etc/freeradius/3.0/sites-enabled/default'
      owner: freerad
      group: freerad
      state: link
      
  - name: Remove EAP symbollic link
    file:
      path: '/etc/freeradius/3.0/mods-enabled/eap'
      state: absent
      
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' awx_web
# 172.18.0.4
    
  - name: Collect the location of the awx_web containers log
    shell: "/usr/bin/docker inspect --format '{''{range.NetworkSettings.Networks}''}{''{.IPAddress}''}{''{end}''}' awx_web"
    register: awx_web_ip

  - debug:
      msg: "{{ awx_web_ip.stdout }}"

  - name: Template the clients.conf file
    template:
      src: "{{ role_path }}/clients.conf.j2"
      dest: /etc/freeradius/3.0/clients.conf
      owner: freerad
      group: freerad
      mode: '0640'

  - name: Allow container access to UDP port 1812 with UFW
    ufw:
      rule: allow
      port: '1812'
      from_ip: "{{ awx_web_ip.stdout }}/29"
      proto: udp
      
  - name: Disable 'inner-tunnel' config by removing link
    file:
      path: /etc/freeradius/3.0/sites-enabled/inner-tunnel
      state: absent

  - name: Disable 'control-socket' config by removing link
    file:
      path: /etc/freeradius/3.0/sites-enabled/control-socket
      state: absent
    
  - name: Restart the FreeRADIUS service
    systemd:
      state: restarted
      name: freeradius

  tags: setup-radius
