
- block:
  - name: Collect Debian version from Wireguard server
    command: lsb_release -c
    register: debian_version

  - name: Setting facts for checking the release
    set_fact:
      buster_string: "buster"
      bullseye_string: "bullseye"

  - name: Add buster-backports repository into sources list
    apt_repository:
      repo: deb http://deb.debian.org/debian buster-backports main
      state: present
    when: buster_string in debian_version.stdout

  - name: Install FreeRADIUS packages for Debian 10
    apt:
      pkg:
       - freeradius
       - freeradius-python3
       - python3-requests-oauthlib
      default_release: buster-backports
    when: buster_string in debian_version.stdout

  - name: Install FreeRADIUS packages for Debian 11
    apt:
      pkg:
       - freeradius
       - freeradius-python3
       - python3-requests-oauthlib
    when: bullseye_string in debian_version.stdout

  - name: Force FreeRADIUS auth-type PAP
    lineinfile:
      path: '/etc/freeradius/3.0/users'
      line: "DEFAULT\t\tAuth-Type = pap"

  - name: Install custom exec module
    copy:
      src: "{{ role_path }}/exec"
      dest: '/etc/freeradius/3.0/mods-available/'
      owner: root
      group: root
      mode: '0644'

  - name: Install FreeRADIUS exec mod enabled link
    file:
      src: '/etc/freeradius/3.0/mods-available/exec'
      dest: '/etc/freeradius/3.0/mods-enabled/exec'
      owner: freerad
      group: freerad
      state: link

  - name: Template the oauth2-oracle.py file
    template:
      src: "{{ role_path }}/oauth2-oracle.py.j2"
      dest: /usr/local/bin/oauth2-oracle.py
      owner: root
      group: root
      mode: '0755'

  - name: Install custom default config
    copy:
      src: "{{ role_path }}/default"
      dest: '/etc/freeradius/3.0/sites-available/default'
      owner: root
      group: root
      mode: '0644'
      
  - name: Install FreeRADIUS default site enabled link
    file:
      src: '/etc/freeradius/3.0/sites-available/default'
      dest: '/etc/freeradius/3.0/sites-enabled/default'
      owner: freerad
      group: freerad
      state: link
      
  - name: Remove EAP symbollic link
    file:
      path: '/etc/freeradius/3.0/mods-enabled/eap'
      state: absent
      
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' awx_web
# 172.18.0.4
    
  - name: Collect the location of the awx_web containers log
    shell: "/usr/bin/docker inspect --format '{''{range.NetworkSettings.Networks}''}{''{.IPAddress}''}{''{end}''}' awx_web"
    register: awx_web_ip

  - debug:
      msg: "{{ awx_web_ip.stdout }}"

  - name: Template the clients.conf file
    template:
      src: "{{ role_path }}/clients.conf.j2"
      dest: /etc/freeradius/3.0/clients.conf
      owner: freerad
      group: freerad
      mode: '0640'

  - name: Allow container access to UDP port 1812 with UFW
    ufw:
      rule: allow
      port: '1812'
      from_ip: "{{ awx_web_ip.stdout }}/29"
      proto: udp
      
  - name: Disable 'inner-tunnel' config by removing link
    file:
      path: /etc/freeradius/3.0/sites-enabled/inner-tunnel
      state: absent

  - name: Disable 'control-socket' config by removing link
    file:
      path: /etc/freeradius/3.0/sites-enabled/control-socket
      state: absent
    
  - name: Restart the FreeRADIUS service
    systemd:
      state: restarted
      name: freeradius

  tags: setup-radius
