
- block:
  - name: Install FreeRADIUS packages
    apt:
      pkg:
       - freeradius
       - freeradius-python3
       - python3-requests-oauthlib
      default_release: buster-backports

  - name: Enable FreeRADIUS Auth-Type OAUTHOracle
    lineinfile:
      path: '/etc/freeradius/3.0/users'
      line: "DEFAULT\t\tAuth-Type = pap"

  - name: Install custom exec module
    copy:
      src: "{{ role_path }}/exec"
      dest: '/etc/freeradius/3.0/mods-available/'
      owner: root
      group: root
      mode: '0644'

  - name: Install FreeRADIUS exec mod enabled link
    file:
      src: '/etc/freeradius/3.0/mods-available/exec'
      dest: '/etc/freeradius/3.0/mods-enabled/exec'
      owner: freerad
      group: freerad
      state: link

  - name: Template the oauth2-oracle.py file
    template:
      src: "{{ role_path }}/oauth2-oracle.py.j2"
      dest: /usr/local/bin/oauth2-oracle.py
      owner: root
      group: root
      mode: '0755'

  - name: Install custom default config
    copy:
      src: "{{ role_path }}/default"
      dest: '/etc/freeradius/3.0/sites-available/default'
      owner: root
      group: root
      mode: '0644'
      
  - name: Install FreeRADIUS default site enabled link
    file:
      src: '/etc/freeradius/3.0/sites-available/default'
      dest: '/etc/freeradius/3.0/sites-enabled/default'
      owner: freerad
      group: freerad
      state: link
      
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' awx_web
# 172.18.0.4
    
  - name: Collect the location of the awx_web containers log
    shell: "/usr/bin/docker inspect --format '{''{range.NetworkSettings.Networks}''}{''{.IPAddress}''}{''{end}''}' awx_web"
    register: awx_web_ip

  - debug:
      msg: "{{ awx_web_ip.stdout }}"
    
  - name: Insert custom listener config into clients.conf
    blockinfile:
      path: /etc/freeradius/3.0/clients.conf
      block: |
        client {{ awx_web_ip.stdout }} {
                ipaddr		= {{ awx_web_ip.stdout }}
                protocol	= udp
                secret          = {{ radius_secret }}
                shortname       = awx_container
                nastype         = other
        }

  - name: Allow container access to UDP port 1812 with UFW
    ufw:
      rule: allow
      port: '1812'
      from_ip: "{{ awx_web_ip.stdout }}"
      proto: udp
    
  - name: Restart the FreeRADIUS service
    systemd:
      state: restarted
      name: freeradius

# AWX needs to be configured like so:
     
#In the 'Authentication' > 'Radius' page:
#
#RADIUS SERVER:	172.17.0.1
#RADIUS PORT:	1812
#RADIUS SECRET:	"{{ radius_secret }}"

# Close inner-tunnel
# rm /etc/freeradius/3.0/sites-enabled/inner-tunnel

  tags: setup-radius
