
- import_tasks: "{{ role_path }}/tasks/setup_prometheus.yml"
  tags: setup-monitor

- import_tasks: "{{ role_path }}/tasks/setup_nginx_grafana.yml"
  tags: setup-monitor

- import_tasks: "{{ role_path }}/tasks/setup_grafana.yml"
  tags: setup-monitor

