
- name: Install Prometheus and Node-Exporter
  apt:
    pkg:
    - prometheus
    - prometheus-node-exporter
    - jq

- name: Touch the prometheus.yml config file to ensure it exists.
  file:
    path: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
    state: touch

- name: Ensure /usr/local/bin/prometheus exists
  file:
    path: /usr/local/bin/prometheus
    owner: root
    group: root
    mode: '0744'
    state: directory

- name: Save new generate_config.sh script, template
  template:
    src: '{{ role_path }}/generate_config.sh.j2'
    dest: '/usr/local/bin/prometheus/generate_config.sh'
    owner: root
    group: root
    mode: '0744'

- name: Install config_piece_1 file for generating Prometheus config
  copy:
    src: "{{ role_path }}/config_piece_1"
    dest: "/usr/local/bin/prometheus/config_piece_1"
    owner: root
    group: root
    mode: '0644'

- name: Install config_piece_2 file for generating Prometheus config
  copy:
    src: "{{ role_path }}/config_piece_2"
    dest: "/usr/local/bin/prometheus/config_piece_2"
    owner: root
    group: root
    mode: '0644'

- name: Set Prometheus retention period to desired amount of days
  lineinfile:
    path: /etc/default/prometheus
    regexp: '^ARGS=.*$'
    line: 'ARGS="--storage.tsdb.retention={{ prometheus_days_retention }}d"'
    owner: root
    group: root
    mode: '0644'

- name: Install synapse-v2.rules file for Prometheus
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: '0644'
  with_items:
    - { owner: root, src: "{{ role_path }}/synapse-v2.rules", dest: "/etc/prometheus/synapse-v2.rules" }

- name: Creates a crontab entry to generate Prometheus config every 5 minutes
  cron:
    name: "Regenerate Prometheus config"
    minute: "*/5"
    user: root
    job: "/bin/sh /usr/local/bin/prometheus/generate_config.sh"

- name: Ensure service prometheus is started
  service:
    name: prometheus
    state: started

