
# setup nginx proxy for graphana
# install graphana


- name: Install Nginx and Certbot for AWX reverse proxy
  apt:
    pkg:
    - apt-transport-https
    - software-properties-common

- name: Add a GPG signing key for Graphana, will not download if present
  apt_key:
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Graphana repository into sources list
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install Graphana packages
  apt:
    pkg:
    - grafana

# configure graphana
# $ grafana-cli admin reset-admin-password <new password>
# or can just do it graphically, default password for admin is 'admin'

- debug:
    msg: If this is your first time setting up Graphana please login with username 'admin and password 'admin' and set a strong unique administrator password.
