

- name: Install Nginx and Certbot for AWX reverse proxy
  apt:
    pkg:
    - nginx
    - certbot

- name: Save new 'grafana' nginx config file, template
  template:
    src: './roles/setup-monitor/grafana.j2'
    dest: '/etc/nginx/sites-available/grafana'

- name: Create a symbolic link to enable the config
  file:
    src: /etc/nginx/sites-available/grafana
    dest: /etc/nginx/sites-enabled/grafana
    owner: root
    group: root
    state: link

- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  openssl_dhparam:
    path: '/etc/ssl/grafana_dhparam.pem'
    size: 2048

- name: Check that the cert for awx already exists
  stat:
    path: '/etc/letsencrypt/live/{{ grafana_url }}/fullchain.pem'
  register: stat_2_result

- name: Stop service nginx, if started
  service:
    name: nginx
    state: stopped
  when: not stat_2_result.stat.exists

- name: Generate letsencrypt certificate for Grafana if not found
  command: certbot certonly  --noninteractive --standalone --agree-tos -m {{ certbot_email }} -d {{ grafana_url }}
  when: not stat_2_result.stat.exists

- name: Creates a crontab entry to renew certbot"
  cron:
    name: "Renew letsencrypt certificate"
    special_time: daily
    user: root
    job: '/bin/sh /usr/bin/certbot renew --quiet --no-self-upgrade'

- name: Ensure default nginx config is deleted
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure service nginx is started
  service:
    name: nginx
    state: started

