---
- name: "Pre-setup for the GoMatrixHosting AWX system. Also creates a webhook system for MemberPress and a monitoring system based on Graphana."
  hosts: "{{ 'awx_servers' }}"
  become: true

  roles:
    - presetup-awx
    - setup-webhooks
    - setup-monitor
