
- name: Creates an entry like "@reboot /some/job.sh"
  cron:
    name: "Backup AWX to backup.json and run borgmatic"
    special_time: daily
    job: 'su - awx-export -c "/home/awx-export/.local/bin/export-awx.sh" > /var/lib/awx/projects/hosting/backup.json; /usr/bin/borgmatic'
