
- name: Create crontab entry for 'Dump AWX database and run borgmatic'
  cron:
    name: "Dump AWX database and run borgmatic"
    special_time: daily
    job: docker exec -t awx_postgres pg_dump -U awx awx > /var/lib/awx/projects/awx-dump.sql; /usr/bin/borgmatic'
