# IPO Summary:
#
# INPUT:
# PROCESSING: install&configure FreeRADIUS, listens locally only, gateways to wp-oauth-provider
# OUTPUT: notify: restart freeradius

- block:
  - name: Install FreeRADIUS packages
    apt:
      pkg:
       - freeradius
       - freeradius-python3
       - python3-requests-oauthlib
      default_release: buster-backports

  - name: Enable FreeRADIUS Auth-Type OAUTHOracle
    lineinfile:
      path: '/etc/freeradius/3.0/users'
      line: 'DEFAULT		Auth-Type = OAUTHOracle'

  - name: Install FreeRADIUS local-OAUTHOracle virtual host file
    copy:
      src: "{{ role_path }}/local-OAUTHOracle"
      dest: '/etc/freeradius/3.0/sites-available/'
      owner: freerad
      group: freerad
      mode: '0640'

  - name: Install FreeRADIUS local-OAUTHOracle virtual host enabled-link
    ansible.builtin.file:
      src: '../sites-available/local-OAUTHOracle'
      dest: '/etc/freeradius/3.0/sites-enabled/local-OAUTHOracle'
      owner: freerad
      group: freerad
      state: link

  tags: setup-configure-radius
