
- name: Ensure /projects/hosting/awx_tokens.yml file exists
  file:
    path: '/var/lib/awx/projects/hosting/awx_tokens.yml'
    owner: root
    group: root
    mode: '0600'
    state: touch

- name: Insert '#AWX Token' spacer to awx_tokens.yml
  lineinfile:
    path: /var/lib/awx/projects/hosting/awx_tokens.yml
    line: '#AWX Token'
    owner: root
    group: root
    mode: '0600'

- name: Fetch the awx_tokens.yml variable from AWX
  fetch:
    src: /var/lib/awx/projects/hosting/awx_tokens.yml
    dest: /tmp/awx_tokens.yml
    flat: yes

- name: Include AWX master token from awx_tokens.yml
  include_vars:
    file: /tmp/awx_tokens.yml
  no_log: True

- name: Delete the old master token by its id
  awx.awx.tower_token:
    existing_token_id: '{{ awx_master_token_id }}'
    state: absent
    tower_host: "{{ awx_url }}"
    tower_username: "{{ admin_username }}"
    tower_password: "{{ admin_password }}"
  when: awx_master_token_id is defined

#- name: "Collect AWX admin token the hard way! Used if running into this error: https://www.reddit.com/r/awx/comments/lastzb/awx_failed_to_get_token_the_read_operation_times/"
#  delegate_to: 127.0.0.1
#  shell: |
#      curl -sku {{ admin_username }}:{{ admin_password }} -H "Content-Type: application/json" -X POST -d '{"description":"Tower CLI", "application":null, "scope":"write"}' https://{{ awx_url }}/api/v2/users/1/personal_tokens/ | jq '.token' | sed -r 's/\"//g'
#  register: awx_token

- name: Create the master token using username/password
  awx.awx.tower_token:
    description: 'AWX Master Token'
    scope: "write"
    state: present
    tower_host: "{{ awx_url }}"
    tower_username: "{{ admin_username }}"
    tower_password: "{{ admin_password }}"
  register: awx_master_token_creation

- name: Create a AWX session token for the webhook user/role
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_master_token_creation.ansible_facts.tower_token.token }}"
    #tower_oauthtoken: "{{ awx_token.stdout }}"
  register: webhook_session_token_creation

- name: Add awx_master_token line to awx_tokens.yml file on AWX
  lineinfile:
    path: '/var/lib/awx/projects/hosting/awx_tokens.yml'
    insertafter: '# AWX Token'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    mode: '0600'
    state: present
  with_dict:
    'awx_master_token': '{{ awx_master_token_creation.ansible_facts.tower_token.token }}'
#    'awx_master_token': '{{ awx_token.stdout }}'

- name: Add awx_master_token_id line to awx_tokens.yml file on AWX
  lineinfile:
    path: '/var/lib/awx/projects/hosting/awx_tokens.yml'
    insertafter: '# AWX Token'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    mode: '0600'
    state: present
  with_dict:
    'awx_master_token_id': '{{ awx_master_token_creation.ansible_facts.tower_token.id }}'
#    'awx_master_token_id': 'null'
# If used the id needs to be hard coded in before re-running this tasklist!

- name: Add webhook_session_token line to awx_tokens.yml file on AWX
  lineinfile:
    path: '/var/lib/awx/projects/hosting/awx_tokens.yml'
    insertafter: '# AWX Token'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    mode: '0600'
    state: present
  with_dict:
    'webhook_session_token': '{{ webhook_session_token_creation.ansible_facts.tower_token.token }}'
