
- name: Collect username of user running this playbook
  set_fact:
    controller_username: "{{ lookup('env', 'USER') }}"

- name: Clone projects folder repo to local controller
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  git:
    repo: '{{ projects_folder_source }}'
    dest: /tmp/projects/

- name: Ensure /projects/hosting/awx_tokens.yml file exists
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  file:
    path: '/tmp/projects/hosting/awx_tokens.yml'
    #owner: root
    #group: root
    mode: '0600'
    state: touch

- name: Insert '#AWX Token' spacer to awx_tokens.yml
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  lineinfile:
    path: /tmp/projects/hosting/awx_tokens.yml
    line: '#AWX Token'
    #owner: root
    #group: root
    mode: '0600'

- name: Include AWX master token from awx_tokens.yml
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  include_vars:
    file: /tmp/projects/hosting/awx_tokens.yml
  #no_log: True

#- name: Delete the old master token by its id. Unused due to this error: https://www.reddit.com/r/awx/comments/lastzb/awx_failed_to_get_token_the_read_operation_times/"
#  awx.awx.tower_token:
#    existing_token_id: '{{ awx_master_token_id }}'
#    state: absent
#    tower_host: "{{ awx_url }}"
#    tower_username: "{{ admin_username }}"
#    tower_password: "{{ admin_password }}"
#  when: awx_master_token_id is defined

#root@panel:~# kubectl get pods --namespace=awx 
#NAME                                               READY   STATUS    RESTARTS   AGE
#awx-operator-controller-manager-647f4c5c7d-mnr49   2/2     Running   0          57m
#awx-postgres-0                                     1/1     Running   0          55m
#awx-ff5bd7695-x6kgf                                4/4     Running   0          55m

#root@panel:~# kubectl get pods --namespace=awx | grep -E -v 'NAME|awx-operator|awx-postgres' | awk '{print $1}'
#awx-ff5bd7695-x6kgf

- name: "Collect AWX admin token the hacks way! 1"
  shell: |
      kubectl get pods --namespace=awx | grep -v 'NAME\|awx-operator\|awx-postgres' | awk '{print $1}'
  register: awx_pod

- name: "Collect AWX admin token the hacks way! 2"
  command: |
      kubectl exec -n awx -i -t {{ awx_pod.stdout }} --container awx-task -- /bin/bash -c 'awx-manage create_oauth2_token --user admin'
  register: awx_token
  no_log: True

#- name: Create the master token using username/password. Unused due to this error: https://www.reddit.com/r/awx/comments/lastzb/awx_failed_to_get_token_the_read_operation_times/"
#  awx.awx.tower_token:
#    description: 'AWX Master Token'
#    scope: "write"
#    state: present
#    tower_host: "{{ awx_url }}"
#    tower_username: "{{ admin_username }}"
#    tower_password: "{{ admin_password }}"
#  register: awx_master_token_creation

- name: Create a AWX session token for the webhook user/role
#  awx.awx.tower_token:
  awx.awx.token:
    description: 'AWX Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_url }}"
    #tower_oauthtoken: "{{ awx_master_token_creation.ansible_facts.tower_token.token }}"
    tower_oauthtoken: "{{ awx_token.stdout }}"
    validate_certs: no
  register: webhook_session_token_creation

- name: Add awx_master_token line to awx_tokens.yml file
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  lineinfile:
    path: '/tmp/projects/hosting/awx_tokens.yml'
    insertafter: '# AWX Token'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    mode: '0600'
    state: present
  with_dict:
#    'awx_master_token': '{{ awx_master_token_creation.ansible_facts.tower_token.token }}'
    'awx_master_token': '{{ awx_token.stdout }}'

- name: Add awx_master_token_id line to awx_tokens.yml file
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  lineinfile:
    path: '/tmp/projects/hosting/awx_tokens.yml'
    insertafter: '# AWX Token'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    mode: '0600'
    state: present
  with_dict:
#    'awx_master_token_id': '{{ awx_master_token_creation.ansible_facts.tower_token.id }}'
    'awx_master_token_id': 'null'
# If used the id needs to be hard coded in before re-running this tasklist!

- name: Add webhook_session_token line to awx_tokens.yml file
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  lineinfile:
    path: '/tmp/projects/hosting/awx_tokens.yml'
    insertafter: '# AWX Token'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    mode: '0600'
    state: present
  with_dict:
    'webhook_session_token': '{{ webhook_session_token_creation.ansible_facts.tower_token.token }}'

- name: Git Add files for projects folder repo
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  shell: "git add *"
  args:
    chdir: /tmp/projects
  register: gitadd

- debug:
    var: gitadd.cmd

- name: Git Commit for projects folder repo
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  shell: git commit -m "Ansible Backup"
  args:
    chdir: /tmp/projects
  ignore_errors: yes
  register: gitcommit

# Will fail if no updates are found

#TASK [setup-awx : Git Commit for projects folder repo] ****************************************************************
#fatal: [panel.chatoasis.com]: FAILED! => {"changed": true, "cmd": "git commit -m \"Ansible Backup\"", "delta": "0:00:00.002987", "end": "2022-01-27 12:32:25.481962", "msg": "non-zero return code", "rc": 1, "start": "2022-01-27 12:32:25.478975", "stderr": "", "stderr_lines": [], "stdout": "On branch main\nYour branch is up to date with 'origin/main'.\n\nnothing to commit, working tree clean", "stdout_lines": ["On branch main", "Your branch is up to date with 'origin/main'.", "", "nothing to commit, working tree clean"]}

- debug:
    var: gitcommit.stdout

- name: Git Push for projects folder repo
  delegate_to: localhost
  become_user: '{{ controller_username }}'
  shell: git push
  args:
    chdir: /tmp/projects
  when: gitcommit.stdout.find("nothing to commit") == -1
  register: gitpush

- debug:
    var: gitpush
