
- name: Copy k3s.sh script
  copy:
    src: '{{ role_path }}/scripts/k3s.sh'
    dest: /root/k3s.sh
    owner: root
    group: root
    mode: '0600'

- name: Run k3s.sh to install k3s
  shell: |
      sh /root/k3s.sh --write-kubeconfig-mode 644

- name: Download cmctl
  get_url:
    url: https://github.com/jetstack/cert-manager/releases/latest/download/cmctl-linux-amd64.tar.gz
    dest: /usr/local/src/cmctl.tar.gz

- name: Extract cmctl
  unarchive:
    src: /usr/local/src/cmctl.tar.gz
    dest: /usr/local/src
    remote_src: yes

- name: Install cmctl
  copy:
    src: /usr/local/src/cmctl
    dest: /usr/local/bin/cmctl
    remote_src: yes

- name: Git - Check out awx-operator
  git:
    repo: 'https://github.com/ansible/awx-operator.git'
    dest: /root/awx-operator/
    version: 0.15.0
    force: yes

- name: Deploy awx-operator
  shell: |
      export 'NAMESPACE=awx' && make deploy --directory=/root/awx-operator/

- name: Extract awx-on-k3s repo
  unarchive:
    src: '{{ role_path }}/repos/awx-on-k3s.tar.xz'
    dest: /root/

- name: Template base/awx.yml
  template:
    src: '{{ role_path }}/templates/awx.yaml.j2'
    dest: /root/awx-on-k3s/base/awx.yaml
    owner: root
    group: root
    mode: '0640'
    
- name: Template base/kustomization.yml
  template:
    src: '{{ role_path }}/templates/kustomization.yaml.j2'
    dest: /root/awx-on-k3s/base/kustomization.yaml
    owner: root
    group: root
    mode: '0640'

- name: Create /data/postgres directory if it does not exist
  file:
    path: /data/postgres
    state: directory
    mode: '0755'

- name: Create /data/projects directory if it does not exist
  file:
    path: /data/projects
    state: directory
    owner: 1000
    group: 0
    mode: '0755'

- name: Template cert-manager.yaml
  template:
    src: '{{ role_path }}/repos/cert-manager.yaml'
    dest: /root/cert-manager.yaml
    owner: root
    group: root
    mode: '0640'

- name: Apply cert-manager.yaml manifest
  command: |
      kubectl apply -f /root/cert-manager.yaml

- name: Check the cert-manager API until it's ready
  command: |
      cmctl check api --kubeconfig /etc/rancher/k3s/k3s.yaml
  register: result
  until: result.stdout.find("The cert-manager API is ready") != -1
  retries: 30
  delay: 30

- name: Template issuer.yaml
  template:
    src: '{{ role_path }}/templates/issuer.yaml.j2'
    dest: /root/awx-on-k3s/acme/issuer.yaml
    owner: root
    group: root
    mode: '0640'

- name: Deploy the issuer
  command: |
      kubectl apply -k /root/awx-on-k3s/acme

- name: Copy base/middleware.yaml
  template:
    src: '{{ role_path }}/templates/middleware.yaml'
    dest: /root/awx-on-k3s/base/middleware.yaml
    owner: root
    group: root
    mode: '0640'

- name: Apply middleware.yaml to redirect HTTP to HTTPS
  command: |
      kubectl -n default apply -f /root/awx-on-k3s/base/middleware.yaml

- name: Deploy AWX
  command: |
      kubectl apply -k /root/awx-on-k3s/base

- name: Check if AWX is deployed (for up to 15 minutes)
  command: |
      kubectl -n awx logs --tail=10 deployments/awx-operator-controller-manager -c awx-manager
  register: result
  until: result.stdout.find("failed=0") != -1
  retries: 30
  delay: 30

- name: Required objects have been deployed with the AWX Operator in the awx namespace.
  command: |
      kubectl -n awx get awx,all,ingress,secrets

