

- name: Update repositories and all packages on target machine
  apt:
    name: "*"
    update_cache: yes

- name: Install necessary utils on target machine
  apt:
    pkg:
     - etckeeper
     - ansible-tower-cli
     - webhook

- name: Ensure group "webhook" exists
  group:
    name: webhook
    state: present

- name: Add the disabled user account 'webhook' with a specific uid and a primary group of 'webhook'
  user:
    name: webhook
    comment: Webhook user account for webhooks service.
    password: '!'
    group: webhook

- name: webhook systemd unit
  copy:
    src: "{{ role_path }}/webhook.service"
    dest: /etc/systemd/system/webhook.service
    owner: root
    group: root
    mode: '0644'

- name: Install webhook.conf
  copy:
    src: "{{ role_path }}/webhook.conf"
    dest: /etc/webhook.conf
    owner: root
    group: root
    mode: '0644'

- name: Install webhook-run.py executable
  copy:
    src: "{{ role_path }}/webhook-run.py"
    dest: "/usr/local/bin/webhook-run.py"
    owner: root
    group: root
    mode: '0755'

- name: Restart service webhook, in all cases
  service:
    name: webhook
    state: restarted

- name: Configure awx-cli host
  command: |
    sudo -H -u webhook bash -c 'awx-cli config host {{ awx_url }}'

- name: Configure awx-cli username
  command: |
    sudo -H -u webhook bash -c 'awx-cli config username admin'

- name: Configure awx-cli host
  command: |
    sudo -H -u webhook bash -c 'awx-cli config password {{ admin_password }}'




