
# Organisation Settings
org_name: ExampleOrg

# URL Settings
awx_url: panel.example.org
grafana_url: monitor.example.org
certbot_email: myemail@protonmail.com

# Grafana Settings
grafana_admin_password: << strong-password >>

# AWX Settings
admin_username: admin
secret_key: << strong-password >>
pg_password: << strong-password >>
admin_password: << strong-password >>

# Repository Settings
create_delete_source: https://gitlab.com/GoMatrixHosting/ansible-create-delete-subscription-membership.git
create_delete_branch: testing
provision_source: https://gitlab.com/GoMatrixHosting/ansible-provision-server.git
provision_branch: testing
deploy_source: https://gitlab.com/GoMatrixHosting/gomatrixhosting-matrix-docker-ansible-deploy.git
deploy_branch: testing

# SSH Keys
private_ssh_key: /key/location/id_ed25519
private_ssh_key_password: << strong-password >>
vault_unlock_ssh_password: << strong-password >>
public_ssh_key: /key/location/id_ed25519.pub

# FreeRADIUS
radius_secret: << strong-password >>
oauth_client_id: << from wp-oath-provider >>
oauth_client_secret: << from wp-oath-provider >>
wp_url: example.org

# Backup Server Settings
backup_server_ip: 255.255.255.255
backup_server_hostname: hostname
backup_server_user: username
backup_server_directory: '/location/of/backup'
backup_server_location: 'Perth, Western Australia'
backup_encryption_passphrase: << strong-password >>
client_backup_private_ssh_key: /key/location/client_id_ed25519
client_backup_public_ssh_key: /key/location/client_id_ed25519.pub

# DigitalOcean Settings
do_api_token: << do_api_token >>
do_spaces_access_key: << do_spaces_access_key >>
do_spaces_secret_key: << do_spaces_secret_key >>
do_image_master: debian-10-x64

