
# Organisation Settings
org_name: ExampleOrg

# URL settings
awx_url: panel.example.org
grafana_url: monitor.example.org
certbot_email: myemail@protonmail.com

# Grafana Settings
grafana_admin_password: << strong-password >>

# AWX settings
secret_key: << strong-password >>
pg_password: << strong-password >>
admin_password: << strong-password >>

# SSH keys
private_ssh_key: /key/location/id_ed25519
private_ssh_key_password: << strong-password >>
public_ssh_key: /key/location/id_ed25519.pub

# Hosting settings, only needed if setup is being used commercially.
do_api_token: << do_api_token >>
do_spaces_access_key: << do_spaces_access_key >>
do_spaces_secret_key: << do_spaces_secret_key >>
do_image_master: debian-10-x64

