
- name: Copy Debian Testing (Bullseye) sources.list over to host
  copy:
    src: '{{ role_path }}/templates/sources.list'
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Update repositories cache
  apt:
    update_cache: yes

- name: List distro release
  shell: echo $(lsb_release -cs)
  register: distro_release

- name: Perform a 'apt-get dist-upgrade' if OS is still Debian Buster
  apt:
    upgrade: dist
  when: distro_release.stdout == 'buster'

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install necessary packages
  apt:
    pkg:
    - ufw
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - ansible

- name: Allow all access to TCP port 80 with UFW
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow all access to TCP port 443 with UFW
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow all access to TCP port 22 with UFW
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Default allow outgoing traffic with UFW
  ufw:
    policy: allow
    direction: out

- name: Default deny incoming traffic with UFW
  ufw:
    policy: deny
    direction: in

- name: Enable UFW
  ufw:
    state: enabled

- name: Add an Apt signing key, will not download if present
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
    state: present

- name: Add Docker repository into sources list
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian testing stable'
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    pkg:
    - docker-ce
    - docker-compose

- name: Install Node.js pre-requisite packages
  apt:
    pkg:
    - nodejs 
    - npm 
    - git
    - python3-pip 
    - pwgen 
    - python3-docker

- name: Install Docker Compose python package on version 1.21.0
  pip:
    name: docker-compose==1.21.0



