
- name: Install Nginx and Certbot for AWX reverse proxy
  apt:
    pkg:
    - nginx
    - certbot

- name: Save new 'awx' nginx config file, template
  template:
    src: './roles/presetup-awx/templates/awx.j2'
    dest: '/etc/nginx/sites-available/awx'

- name: Create a symbolic link to enable the config
  file:
    src: /etc/nginx/sites-available/awx
    dest: /etc/nginx/sites-enabled/awx
    owner: root
    group: root
    state: link

- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  openssl_dhparam:
    path: '/etc/ssl/awx_dhparam.pem'
    size: 2048

- name: Check that the cert for awx already exists
  stat:
    path: '/etc/letsencrypt/live/{{ awx_url }}/fullchain.pem'
  register: stat_result

- name: Stop service nginx, if started
  service:
    name: nginx
    state: stopped
  when: not stat_result.stat.exists

- name: Generate letsencrypt certificate for AWX if not found
  command: certbot certonly  --noninteractive --standalone --agree-tos -m {{ certbot_email }} -d {{ awx_url }}
  when: not stat_result.stat.exists

- name: Creates a crontab entry to renew certbot"
  cron:
    name: "Renew letsencrypt certificate"
    special_time: weekly
    user: root
    job: '/usr/bin/certbot renew --quiet --no-self-upgrade --pre-hook "service nginx stop" --post-hook "service nginx restart"'

- name: Ensure default nginx config is deleted
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure service nginx is started
  service:
    name: nginx
    state: started



